### ISSUE TITLE
Request: visualkeras

### ISSUE THREAD

**Issue by paulgavrikov** [ashishpatel26/Tools-to-Design-or-Visualize-Architecture-of-Neural-Network#4]
Hi Ashish,

would you mind adding https://github.com/paulgavrikov/visualkeras/? It's a pypi package that allows network architecture generation directly from python and uses your keras model.

**Comment by ashishpatel26** [comment]
Added. Thanks for Contributing.

**Comment by endolith** [comment]
(This issue can be closed)
